images:
  scm-manager: .

volumes:
  scm-manager:
    chown: 65532:65532
    chmod: 0750

jails:
  scm-manager:
    image: scm-manager
    mounts:
      scm-manager: /scm-manager/.scm
    ip4.addr: 127.0.55.1
    env:
      JAVA_HOME: /usr/local/openjdk11
    exec.jail_user: scm-manager
    exec.start: /opt/scm-server/bin/scm-server start
    exec.stop: /opt/scm-server/bin/scm-server stop
