#
# focker compose wordpress.yml
# focker compose wordpress.yml backup
# focker compose wordpress.yml restore
#

images:
  wordpress-5: .

jails:
  wordpress:
    image: wordpress-5
    mounts:
      test-volume2: /mnt/volume2
      test-volume2: /mnt/volume1
    ip4.addr: 127.0.1.1

volumes:
  test-volume2: {}
  test-volume2: {}

commands:
  backup:
    jail: wordpress
    command: |
      mysqldump >/mnt/volume2/backup.sql
    mounts:
      test-volume2: /mnt/volume2

  restore:
    jail: wordpress
    command: |
      mysql </mnt/volume2/backup.sql
